version: '3.2'

services:
  web:
    build: ./src
    restart: on-failure
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
        - 8282:8000
    environment:
      DEBUG: 0
      ALLOWED_HOST: "${ALLOWED_HOST}"
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
    - static_volume:/usr/src/app/static
    - media_volume:/usr/src/app/media

volumes:
  static_volume:
  media_volume:


