# Generated by Django 3.2 on 2021-04-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("origin_url", models.CharField(max_length=2083)),
                ("short_link", models.CharField(max_length=255)),
                ("views", models.BigIntegerField(default=0)),
            ],
        ),
    ]
