# Generated by Django 3.2 on 2021-05-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="permanent",
            field=models.BooleanField(default=False),
        ),
    ]
