# Generated by Django 3.2 on 2021-04-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="short_link",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
