# Generated by Django 3.2 on 2021-05-24 02:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="confirmation_code",
            field=models.UUIDField(
                default=uuid.UUID("26b040d0-fe78-46d8-9989-7a19d9d6539e"),
                editable=False,
            ),
        ),
    ]
