# Generated by Django 3.2.3 on 2021-05-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="file_exist",
            field=models.BooleanField(default=True),
        ),
    ]
